
name: Python benchmarking using pytest
on:
        pull_request:
                branches:
                        [master,johans_test]
jobs:
        benchmark:
                name: pytest-benchmarking
                runs-on: ubuntu-latest
                steps:
                        - uses: actions/checkout@v2 
                        - uses: actions/setup-python@v1
                        - name: Installing and running pytest
                          run: |
                                pwd
                                python -m pip install --upgrade pip
                                if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
                                python test.py
                                pytest benchmarking.py --benchmark-json output.txt
                        - name: Push chanes to repo
                          run: |
                                REMOTE=https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
                                git config user.email "${{ github.actor }}@users.noreply.github.com"
                                git config user.name "${{ github.actor }}"
                                git branch
                                git pull ${REMOTE} master --allow-unrelated-histories
                                git checkout master
                                git add output.txt
                                git status
                                git commit -am "testing to push output"
                                git push ${REMOTE} master
