name: Python benchmarking using pytest
on:
        pull_request:
                branches:
                        - master
jobs:
        benchmark:
                name: pytest-benchmarking
                runs-on: ubuntu-latest
                steps:
                        - uses: actions/checkout@v2
                        - name: python test
                          run: |
                                pwd
                                python -m pip install --upgrade pip
                                if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
                                python test.py

